{{- if .Values.image_pull_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-image-pull-secret"
  namespace: "{{ .Release.Namespace }}"
data:
  .dockerconfigjson: {{ .Values.image_pull_secret }}
type: kubernetes.io/dockerconfigjson
{{- end }}