apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: "{{ .Release.Name }}-port"
      protocol: TCP
      targetPort: 8080
      port: 8080