apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-allow-all-ingress"
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  ingress:
    - {}
  policyTypes:
    - Ingress