kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    app: {{ .Release.Name }}
  name: "{{ .Release.Name }}-ingress"
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.hmp_httpd_subdomain }}.{{ .Values.router_url_suffix }}
    http:
      paths:
      - backend:
          service:
            name: "{{ .Release.Name }}-svc"
            port:
              number: 8080
        path: /
        pathType: Prefix